In [1]:
x=5
m=6
y="9"
z="2"
print(type(x))
print(type(y))
print(x+m)
print(y+z)

<class 'int'>
<class 'str'>
11
92


In [2]:
#typecasting
a=int(z)
print(a+m)


8


In [3]:
#list
l1=['hi',1,7,'list',6.7,9.5,[3,59,'hello']]
l2=l1[6][2]
print(l2)
length=len(l1)
print(length)

hello
7


In [4]:
nums=[]
nums.append(21)
nums.append(40.5)
nums.append("string")
print(nums)

[21, 40.5, 'string']


In [5]:
#tuple
t1=(1,2,3,4,5,6)
print(t1)



(1, 2, 3, 4, 5, 6)


In [6]:
#dictionary
d1={'name':'xyz','age':12, 'proff':'students'}
print(d1)
print(type(d1))
print(d1.keys())
print(d1.items())
print(d1.values())
print(d1['name'])

{'name': 'xyz', 'age': 12, 'proff': 'students'}
<class 'dict'>
dict_keys(['name', 'age', 'proff'])
dict_items([('name', 'xyz'), ('age', 12), ('proff', 'students')])
dict_values(['xyz', 12, 'students'])
xyz


In [23]:
num1=int(input("enter a num1:"))
num2=int(input("enter a num2:"))
num3=num1*num2
print("product is:",num3)


enter a num1:4
enter a num2:5
product is: 20


In [8]:
import numpy as np

arr = np.array( [[ 1, 2, 3],
				[ 4, 2, 5]] )
print("Array is of type: ", type(arr))
print("No. of dimensions: ", arr.ndim)
print("Shape of array: ", arr.shape)
print("Size of array: ", arr.size)
print("Array stores elements of type: ", arr.dtype)

Array is of type:  <class 'numpy.ndarray'>
No. of dimensions:  2
Shape of array:  (2, 3)
Size of array:  6
Array stores elements of type:  int64


In [9]:
import numpy as np
arr = np.array([1, 2, 3])
print("Array with Rank 1: \n",arr)
arr = np.array([[1, 2, 3],
                [4, 5, 6]])
print("Array with Rank 2: \n", arr)
arr = np.array((1, 3, 2))
print("\nArray created using "
      "passed tuple:\n", arr)

Array with Rank 1: 
 [1 2 3]
Array with Rank 2: 
 [[1 2 3]
 [4 5 6]]

Array created using passed tuple:
 [1 3 2]


In [10]:
import numpy as np
arr = np.array([2, 4, 6, 8, 10])
c = arr.copy()
print("id of arr", id(arr))
print("id of c", id(c))
arr[0] = 12
print("original array- ", arr)
print("copy- ", c)


id of arr 132879058350224
id of c 132879058350704
original array-  [12  4  6  8 10]
copy-  [ 2  4  6  8 10]


In [11]:
def sum(array):
	sum = 0
	for i in array:
		sum += i
	return sum
testArray = [1, 3, 34, 92, 29, 48, 20.3]
print('The sum of your numbers is ' + str(sum(testArray)))

The sum of your numbers is 227.3


In [12]:
import numpy as np
a = np.arange(10, 1, -2)
print("\n A sequential array with a negative step: \n",a)
newarr = a[np.array([3, 1, 2 ])]
print("\n Elements at these indices are:\n",newarr)


 A sequential array with a negative step: 
 [10  8  6  4  2]

 Elements at these indices are:
 [4 8 6]


In [13]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:5])
print(arr[4:])
print(arr[:4])
print(arr[-3:-1])
print(arr[1:5:2])
print(arr[::2])


[2 3 4 5]
[5 6 7]
[1 2 3 4]
[5 6]
[2 4]
[1 3 5 7]


In [14]:
import numpy as np
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[1, 1:4])
print(arr[0:2, 2])
print(arr[0:2, 1:4])

[7 8 9]
[3 8]
[[2 3 4]
 [7 8 9]]


In [15]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 44
print(arr)
print(x)

[44  2  3  4  5]
[1 2 3 4 5]


In [16]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 65
print(arr)
print(x)

[65  2  3  4  5]
[65  2  3  4  5]


In [17]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
x[0] = 64
print(arr)
print(x)

[64  2  3  4  5]
[64  2  3  4  5]


In [18]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
y = arr.view()
print(x.base)
print(y.base)

None
[1 2 3 4 5]


In [19]:
import numpy as np

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('shape of array :', arr.shape)

[[[[[1 2 3 4]]]]]
shape of array : (1, 1, 1, 1, 4)


In [20]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
new_arr = arr.reshape(4, 3)
print(new_arr)
new_arr = arr.reshape(2, 3, 2)
print(new_arr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [24]:
import numpy as np
x = np.array([[1, 2], [4, 5]])
y = np.array([[7, 8], [9, 10]])
print ("The element wise addition of matrix is : ")
print (np.add(x,y))
print ("The element wise subtraction of matrix is : ")
print (np.subtract(x,y))
print ("The element wise division of matrix is : ")
print (np.divide(x,y))

The element wise addition of matrix is : 
[[ 8 10]
 [13 15]]
The element wise subtraction of matrix is : 
[[-6 -6]
 [-5 -5]]
The element wise division of matrix is : 
[[0.14285714 0.25      ]
 [0.44444444 0.5       ]]


In [25]:
import pandas as pd

dataset = {'cars': ["BMW", "Volvo", "Ford"],'passings': [4, 8, 2]}
myvar = pd.DataFrame(dataset)
print(myvar)

    cars  passings
0    BMW         4
1  Volvo         8
2   Ford         2


In [26]:
import pandas as pd
print(pd.__version__)

2.0.3


In [27]:
import pandas as pd

a = [3, 9, 6]
myvar = pd.Series(a)
print(myvar)
print(myvar[0])

0    3
1    9
2    6
dtype: int64
3


In [28]:
import pandas as pd

a = [3, 9, 6]
myvar = pd.Series(a, index = ["x", "y", "z"])
print(myvar)
print(myvar["y"])

x    3
y    9
z    6
dtype: int64
9


In [29]:
import pandas as pd

data = {"calories": [420, 380, 390],
  "duration": [50, 40, 45]}
df = pd.DataFrame(data)
print(df)
print(df.loc[0])
print(df.loc[[0, 1]])


   calories  duration
0       420        50
1       380        40
2       390        45
calories    420
duration     50
Name: 0, dtype: int64
   calories  duration
0       420        50
1       380        40


In [30]:
import pandas as pd

df = pd.read_csv('Data.csv')

print(df.to_string())

   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes


In [31]:
import pandas as pd
df = pd.read_csv('Data.csv')
print(df)

   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes


In [32]:
import pandas as pd
print(pd.options.display.max_rows)

60


In [33]:
data = {"Duration":{  "0":60,"1":60, "2":60,"3":45,"4":45,"5":60},
  "Pulse":{"0":110,"1":117, "2":103, "3":109,"4":117, "5":102},
  "Maxpulse":{"0":130,"1":145,"2":135,"3":175,  "4":148,"5":127},
  "Calories":{ "0":409,"1":479,"2":340,"3":282,"4":406,"5":300}}

df = pd.DataFrame(data)
print(df)


   Duration  Pulse  Maxpulse  Calories
0        60    110       130       409
1        60    117       145       479
2        60    103       135       340
3        45    109       175       282
4        45    117       148       406
5        60    102       127       300


In [34]:
import pandas as pd

# first data frame
df1 = pd.DataFrame({"fruit" : ["apple", "banana", "mango"],"market_price" : [21, 14, 35]})
display("first DataFrame")
display(df1)

# second Data Frame
df2 = pd.DataFrame({"fruit" : ["banana", "apple", "mango"],"wholesaler_price" : [67, 70, 71]})
display("second DataFrame")
display(df2)

# joining Data Frames
display("merged DataFrame")
pd.merge(df1, df2, on = "fruit", how = "inner")


'first DataFrame'

fruit  market_price
0   apple            21
1  banana            14
2   mango            35

'second DataFrame'

fruit  wholesaler_price
0  banana                67
1   apple                70
2   mango                71

'merged DataFrame'

fruit  market_price  wholesaler_price
0   apple            21                70
1  banana            14                67
2   mango            35                71

In [35]:
import pandas as pd
df = pd.read_csv("Data.csv")
print(df.head())    #Return 5 top rows


   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes


In [36]:
gk = df.groupby('Age')
gk.first()

Country   Salary Purchased
Age                             
27.0    Spain  48000.0       Yes
30.0  Germany  54000.0        No
35.0   France  58000.0       Yes
37.0   France  67000.0       Yes
38.0    Spain  61000.0        No
40.0  Germany      NaN       Yes
44.0   France  72000.0        No
48.0   France  79000.0       Yes
50.0  Germany  83000.0        No

In [37]:
gk.get_group(48)

Country   Age   Salary Purchased
7  France  48.0  79000.0       Yes

In [38]:
#Indentation
j = 1
while(j<= 5):
	print(j)
	j = j + 1

1
2
3
4
5


In [39]:
i=1
while i<=5 :
  print(i*"*")
  i=i+1

*
**
***
****
*****
